<<<<<<< HEAD
<<<<<<< HEAD
project: developerportal

audience: designer

product: all

platform: all

version: all

topnav_title: Jekyll for Designers

topnav_version: 2.1

homepage_title: Doc theme for Jekyll 

site_title: Documentation theme for Jekyll

tagline: Guide for designers

baseurl: "/developerportal"

port: 4006

host: 127.0.0.1 

url: "http://benjaminanding.github.io"

feedback_email: sdk@affectiva.com

sidebar_accordion: true

disqus_shortname: devaffdex

google_analytics:  

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments

print: false

floating_nav: true

# suffix: index.html

exclude: 
  - _drafts
  - bower_components
  - .idea 
  - _site

permalink: :title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      tooltip: true
      search: true

sass:
    sass_dir: _sass

collections:
  tooltips:
    output: true
=======
=======
>>>>>>> parent of 756b936... complete overhaul, template te in use now
# Site settings
title: developer.affdex
email: sdk@affectiva.com
description: For developer use in conjunction with Affectiva's Affdex 
baseurl:  http://benjaminanding.github.io
url:  /developerportal
twitter_username: #
github_username:  #

# Build settings
markdown: kramdown
<<<<<<< HEAD
>>>>>>> parent of 756b936... complete overhaul, template te in use now
=======
>>>>>>> parent of 756b936... complete overhaul, template te in use now
