# Site settings
title: developer.affdex
email: sdk@affectiva.com
description: For developer use in conjunction with Affectiva's Affdex 
baseurl: http://benjaminanding.github.io
url: /developerportal
twitter_username: #
github_username:  #

# Build settings
markdown: kramdown
