# Site settings
title: "Affdex SDK Developer Portal"
email: sdk@affectiva.com
description: > For developer use in conjunction with Affectiva's Affdex 
baseurl: /DeveloperPortal/
url: http://benjaminanding.github
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
