# mandatory definitions
project: developerportal

audience: writer

product: all

platform: all

version: all

topnav_title: developer.affdex

topnav_version: "1.0"

tagline: Guide for Developers

baseurl: "/developerportal/writer" 

port: 4008

destination: ../developerportal-builds/writer

homepage_title: Doc theme for Jekyll -- writer version

site_title: Documentation theme for Jekyll -- designer version
