project: developerportal

audience: designer

product: all

platform: all

version: all

topnav_title: Affdex SDK

topnav_version: 2.0

tagline: Guide for designers

baseurl: "/developerportal/designer"

port: 4006

homepage_title: Affdex SDK -- designer version

site_title: Affdex SDK -- designer version