################################
########Current Versions########
################################
- platform: Android
  architecture: "ARM7"
  version: "SDK 3.0.1"
  url: http://maven.affectiva.com/com/affectiva/android/affdexsdk/3.0.1/affdexsdk-3.0.1.aar
  size: 6.5 MB

- platform: iOS
  architecture: "Universal"
  version: "SDK 3.0.1"
  url: http://affdex-sdk-dist.s3-website-us-east-1.amazonaws.com/ios/affdex-sdk_iOS_3_0_1_374.zip
  size: 107.2 MB

- platform: Windows
  architecture: x86
  version: "SDK 3.0"
  url: http://affdex-sdk-dist.s3-website-us-east-1.amazonaws.com/windows/AffdexSDK-3.0-961-win32.exe
  size: 19.1 MB

- platform: Windows
  architecture: x64
  version: "SDK 3.0"
  url: http://affdex-sdk-dist.s3-website-us-east-1.amazonaws.com/windows/AffdexSDK-3.0-275-win64.exe
  size: 30.4 MB
################################
################################
################################
